services:
  - type: web
    name: campuskart
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGO_URI
        value: mongodb+srv://admin:admin@cluster0.yhwe1ua.mongodb.net/
      - key: JWT_SECRET
        value: your_jwt_secret_key_here
      - key: CLOUDINARY_CLOUD_NAME
        value: dhh8k1los
      - key: CLOUDINARY_API_KEY
        value: "258747662115149"
      - key: CLOUDINARY_API_SECRET
        value: F2X4Ix-jCTmqz5ITqij9PK6BXWw
